server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
      routes:
      - id: payment-route
        uri: lb://cloud-payment-service
        filters:
        - AddRequestHeader=X-Request-id, payment  #必须包含请求头X-Request-id，且值为payment
        predicates:
        - Path = /payment/get/**

eureka:
  client:
    #表示将自己注册进EurekaServer
    register-with-eureka: true
    #表示检索服务注册信息
    fetch-registry: true
    #集群配置
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

